### ISSUE TITLE
Proposal: move language plugins to their own directory

### ISSUE THREAD

**Issue by data-man** [lite-xl/lite-xl-plugins#219] opened 2023-03-01 15:36 UTC

**Comment by Guldoman** [comment] 2023-03-01 15:44
Duplicate of #83.

This would break the setup of people that symlinked the language plugins to their plugins directory.

**Closed by Guldoman** 2023-03-01 15:44 UTC
Labels: duplicate

**Comment by data-man** [comment] 2023-03-01 16:00
> symlinked the language plugins to their plugins directory

This is exactly why I am suggesting this.
I want symlink all `languages` only.

**Comment by Guldoman** [comment] 2023-03-01 16:05
People that symlinked language plugins from this repo would have to recreate the links, so it would be better to avoid breaking their setup.

Also, now that [lpm](https://github.com/lite-xl/lite-xl-plugin-manager) is close to a 1.0 release, people won't need to clone this repo anymore, and will just use that instead.
