### ISSUE TITLE
[BUG] Minimap causes editor to crash

### ISSUE THREAD

**Issue by SOG-web** [lite-xl/lite-xl-plugins#186] opened 2023-01-01 09:40 UTC
Error: C:\Users\SOG\.config\lite-xl/plugins\minimap.lua:467: attempt to index a nil value (local 'color')
stack traceback:
	C:\Users\SOG\.config\lite-xl/plugins\minimap.lua:467: in function 'plugins.minimap.draw'
	...\chocolatey\lib\lite-xl\tools\lite-xl\data/core\view.lua:302: in function 'core.view.draw_scrollbar'
	...ocolatey\lib\lite-xl\tools\lite-xl\data/core\docview.lua:547: in upvalue 'old_draw'
	...\lib\lite-xl\tools\lite-xl\data/plugins\linewrapping.lua:512: in upvalue 'draw'
	C:\Users\SOG\.config\lite-xl/plugins\motiontrail.lua:51: in function 'core.docview.draw'
	...\chocolatey\lib\lite-xl\tools\lite-xl\data/core\node.lua:588: in function 'core.node.draw'
	...\chocolatey\lib\lite-xl\tools\lite-xl\data/core\node.lua:32: in function 'core.node.propagate'
	...\chocolatey\lib\lite-xl\tools\lite-xl\data/core\node.lua:593: in function 'core.node.draw'
	...\chocolatey\lib\lite-xl\tools\lite-xl\data/core\node.lua:31: in function 'core.node.propagate'
	...\chocolatey\lib\lite-xl\tools\lite-xl\data/core\node.lua:593: in function 'core.node.draw'
	...	(skipping 5 levels)
	...\lib\lite-xl\tools\lite-xl\data/plugins\autocomplete.lua:571: in upvalue 'root_view_draw'
	...atey\lib\lite-xl\tools\lite-xl\data/plugins\treeview.lua:498: in upvalue 'root_view_draw'
	...y\lib\lite-xl\tools\lite-xl\data/plugins\contextmenu.lua:31: in function 'core.rootview.draw'
	...\chocolatey\lib\lite-xl\tools\lite-xl\data/core/init.lua:1340: in function 'core.step'
	...\chocolatey\lib\lite-xl\tools\lite-xl\data/core/init.lua:1384: in upvalue 'core_run'
	C:\Users\SOG\.config\lite-xl/plugins\profiler/init.lua:78: in upvalue 'core_run'
	C:\Users\SOG\.config\lite-xl/plugins\settings.lua:1867: in upvalue 'core_run'
	C:\Users\SOG\.config\lite-xl/plugins\ipc.lua:858: in function 'core.run'
	(...tail calls...)
	[string "local core..."]:9: in function <[string "local core..."]:2>
	[C]: in function 'xpcall'
	[string "local core..."]:2: in main chunk

**Comment by Guldoman** [comment] 2023-01-01 19:05
This is likely caused by some plugin that touches your theme. Do you have any installed?

**Comment by SOG-web** [comment] 2023-01-01 22:30
Yes it was a plugin, After removing minimap plugin and four others It stop show errors

**Comment by Guldoman** [comment] 2023-01-01 22:40
Could you find out which one was the problem specifically? This way we could fix it.

**Comment by adamharrison** [comment] 2023-01-22 04:58
Closing this for now; please feel free to reopen @SOG-web if you do track down what was causing it.

**Closed by adamharrison** 2023-01-22 04:58 UTC
